Disable storage
wikimedia/restbase pull request #1330
Opened 2023-08-24 20:15 UTC by brightbyte

Allow storage of parsoid output to be disabled based on the domain parameter

2023-09-15 14:40 UTC, brightbyte commented on config.fullstack.test.yaml
> +                    grace_ttl: 1000007
These changes should probably not be in this patch.
Though I can't test without https...

2023-09-15 14:40 UTC, brightbyte commented on projects/sys/default.wmf.yaml
> +          disabled_storage: '{{options.parsoid.disabled_storage}}'
is this actually needed? not sure...

2023-09-15 14:42 UTC, brightbyte commented on test/features/pagecontent/language_variants.js
> +            assert.deepEqual('Das ist eine testseite.', res.body.extract);
The content of the page on beta was actually changed! Took me forever to figure that out...

https://de.wikipedia.beta.wmflabs.org/w/index.php?title=RESTBase_Testing_Page&diff=prev&oldid=30418

2023-09-15 14:43 UTC, brightbyte commented on test/features/pagecontent/rerendering.js
should not be in this patch

2023-09-15 14:43 UTC, brightbyte commented on test/features/pagecontent/pagecontent.js
should not be in this patch

2023-09-21 10:21 UTC, johngian requested changes

2023-09-21 10:21 UTC, johngian commented on sys/parsoid.js
> +                        res.headers.etag = mwUtil.makeETag(res.headers['content-revision-id'] || '0', uuid);
I think here we are missing some DOM manipulation that't happening on `generateAndSave` to pass the tid to html meta.

2023-09-21 10:21 UTC, johngian commented on sys/parsoid.js
> +                        res.headers.etag = mwUtil.makeETag(res.headers['content-revision-id'] || '0', uuid);
https://github.com/wikimedia/restbase/blob/6a8e93390e59552e01d296e0563c9ef3ae1867bb/sys/parsoid.js#L444

2023-09-21 10:30 UTC, johngian commented
Do we have a phab ticket for reference?

2023-09-21 18:36 UTC, brightbyte commented
> Do we have a phab ticket for reference?

https://phabricator.wikimedia.org/T344945

2023-09-21 18:38 UTC, brightbyte commented
> It might also be useful to add a header for the fact that parsoid storage is disabled on responses and add a test to assert that for a test wiki from the local env setup.

Something like `x-restbase-cache-disabled`?

2023-09-22 07:39 UTC, brightbyte commented on sys/parsoid.js
> +              throw error;
I don't remember exactly, but I often do this kind of thing when I want to be able to set a break point.

2023-09-22 07:52 UTC, johngian commented
> > It might also be useful to add a header for the fact that parsoid storage is disabled on responses and add a test to assert that for a test wiki from the local env setup.
> 
> Something like `x-restbase-cache-disabled`?

Yeah, so we know what kind of requests we are getting (in case we need to debug from the client side) and also to be able to test this.

2023-09-22 08:59 UTC, brightbyte commented
> > Something like `x-restbase-cache-disabled`?
> 
> Yeah, so we know what kind of requests we are getting (in case we need to debug from the client side) and also to be able to test this.

I implemented it in the latest version.

2023-09-29 18:48 UTC, brightbyte commented
For the record, I don't understand why the "should render & re-render independent revisions" test is now failing with storage enabled. The behavior for that case shouldn't have changed at all. Did I actually break something, or is it an unrelated issue?...

2023-10-11 13:07 UTC, johngian approved these changes

2023-10-11 13:52 UTC, merged