no-cache requests write to cache even when storage is disabled.
wikimedia/restbase pull request #1334
Opened 2023-10-12 18:33 UTC by brightbyte

So allow us to safely switch back from disabled_storage, we need to keep pre-generated cache entries up to date. We can do this by simply continuing to handle no-cache requests as we did before, allowing them to write updated renderings to the cache.

Change-Id: Ica6f52b362d37765471ab1ed37dee62a8e0ca6f7

2023-10-12 18:33 UTC, brightbyte commented
Not sure how to tst this properly

2023-10-17 06:44 UTC, brightbyte commented
All runs got stuck at _"should transparently create a new HTML revision for Main_Page"_.

2023-10-17 07:21 UTC, brightbyte commented
I can reproduce this locally when running `npm run coverage`. Investigating...

2023-10-17 07:55 UTC, brightbyte commented
I have not been able to narrow this down any more than to running `./node_modules/.bin/mocha --timeout 0 test/features/`. There seems to be some interaction between tests that least to a deadlock or infinite retry loop.

Here's the repeated stack trace formatted properly:
```
{
  "name": "restbase-test",
  "hostname": "fv-az559-145",
  "pid": 2103,
  "level": 50,
  "err": {
    "message": "ESOCKETTIMEDOUT",
    "name": "restbase",
    "stack": "HTTPError: ESOCKETTIMEDOUT
    at request.then (/home/runner/work/restbase/restbase/node_modules/preq/index.js:246:19)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at tryCatcher (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/runner/work/restbase/restbase/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
    at process.topLevelDomainCallback (domain.js:126:23)",
    "status": 504,
    "headers": {
      "content-type": "application/problem+json"
    },
    "body": {
      "type": "internal_http_error",
      "detail": "ESOCKETTIMEDOUT",
      "internalStack": "Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/runner/work/restbase/restbase/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:198:13)
    at ClientRequest.EventEmitter.emit (domain.js:466:23)
    at Socket.emitRequestTimeout (_http_client.js:673:40)
    at Object.onceWrapper (events.js:286:20)
    at Socket.emit (events.js:198:13)
    at Socket.EventEmitter.emit (domain.js:466:23)
    at Socket._onTimeout (net.js:443:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)",
      "internalURI": "http://127.0.0.1:8085/v1/events",
      "internalQuery": "{}",
      "internalErr": "ESOCKETTIMEDOUT",
      "internalMethod": "post"
    },
    "root_req": {
      "method": "post",
      "uri": "/fake.fakepedia.org/v1/events/",
      "headers": {
        "content-length": "113",
        "content-type": "application/json",
        "x-client-ip": "::ffff:127.0.0.1",
        "x-forwarded-for": "::ffff:127.0.0.1",
        "x-request-id": "266a31d0-6c3e-11ee-a091-fb429aa93412",
        "x-request-class": "internal"
      }
    },
    "request_id": "266a31d0-6c3e-11ee-a091-fb429aa93412",
    "api_path": "/fake.fakepedia.org/v1/events/",
    "levelPath": "error/events/emit"
  },
  "msg": "ESOCKETTIMEDOUT",
  "time": "2023-10-16T16:09:48.340Z",
  "v": 0
}
```

2023-10-17 09:38 UTC, johngian requested changes

2023-10-17 09:38 UTC, johngian commented on test/features/pagecontent/pagecontent.js
> +        return preq.get( { uri, ...opt } );
Here you are passing `domain` as an attribute to the underlying request library and it throws an error that is not handled that's why it gets stuck.

2023-10-17 09:38 UTC, johngian commented on test/features/pagecontent/pagecontent.js
> +        return preq.get( { uri, ...opt } );
```suggestion
        return preq.get( { uri } );
```

2023-10-17 09:38 UTC, johngian commented on test/features/pagecontent/pagecontent.js
> +        return preq.get( { uri, ...opt } );
This ^ fixes things locally

2023-10-18 16:45 UTC, brightbyte commented on test/features/pagecontent/pagecontent.js
> +        return preq.get( { uri, ...opt } );
Should be fixed now.

2023-10-19 08:57 UTC, johngian approved these changes

2023-10-19 08:58 UTC, merged